server:
  port: 7011
#spring:
#  thymeleaf:
#    prefix: classpath:/static/

spring:
  application:
    name: IMP-MONITOR

eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://172.16.36.88:1111/eureka/
my-monitor:
  enable: false
