server:
  port: 7011
#spring:
#  thymeleaf:
#    prefix: classpath:/static/
spring:
  application:
    name: IMP-MONITOR

eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: xxxx


env:
  online: true

myMonitor:
  eurekaAppsUrl: xxxx
  #可以用逗号隔开
  ignoreApps: CONFIG-SERVER,IMP-MONITORM

  zkUrl: xxxx

influxdb:
  url: http://xxxx:8086
  username: admin
  password: admin
  dbname: influxdb_online
