server:
  port: 7011
#spring:
#  thymeleaf:
#    prefix: classpath:/static/
spring:
  application:
    name: IMP-MONITOR

eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://common1.eureka.s.ttacp8:1111/eureka/,http://common2.eureka.s.ttacp8:1111/eureka/,http://common3.eureka.s.ttacp8:1111/eureka/,http://common4.eureka.s.ttacp8:1111/eureka/

my-monitor:
  enable: true
  eurekaApps-url: http://172.18.80.166:1111/eureka/apps
  #可以用逗号隔开
  ignore-apps: CONFIG-SERVER,IMP-MONITOR
influxdb:
  url: http://172.18.64.95:8086
  username: admin
  password: admin
  dbname: hystrixdb

zookeeper:
  address: