// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.netflix.hystrix.dashboard.data.netty.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *注册类型
   * </pre>
   *
   * Protobuf enum {@code message.RegType}
   */
  public enum RegType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *localCient客户端注册
     * </pre>
     *
     * <code>LOCAL_CLIENT = 1;</code>
     */
    LOCAL_CLIENT(1),
    /**
     * <pre>
     *proxy代理注册
     * </pre>
     *
     * <code>PROXY_CLIENT = 2;</code>
     */
    PROXY_CLIENT(2),
    ;

    /**
     * <pre>
     *localCient客户端注册
     * </pre>
     *
     * <code>LOCAL_CLIENT = 1;</code>
     */
    public static final int LOCAL_CLIENT_VALUE = 1;
    /**
     * <pre>
     *proxy代理注册
     * </pre>
     *
     * <code>PROXY_CLIENT = 2;</code>
     */
    public static final int PROXY_CLIENT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RegType valueOf(int value) {
      return forNumber(value);
    }

    public static RegType forNumber(int value) {
      switch (value) {
        case 1: return LOCAL_CLIENT;
        case 2: return PROXY_CLIENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RegType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RegType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RegType>() {
            public RegType findValueByNumber(int number) {
              return RegType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final RegType[] VALUES = values();

    public static RegType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RegType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.RegType)
  }

  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 requestId = 1;</code>
     */
    boolean hasRequestId();
    /**
     * <code>required int32 requestId = 1;</code>
     */
    int getRequestId();
  }
  /**
   * <pre>
   *心跳
   * </pre>
   *
   * Protobuf type {@code message.HeartBeat}
   */
  public  static final class HeartBeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.HeartBeat)
      HeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeat() {
      requestId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.class, com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private int requestId_;
    /**
     * <code>required int32 requestId = 1;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 requestId = 1;</code>
     */
    public int getRequestId() {
      return requestId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, requestId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat)) {
        return super.equals(obj);
      }
      com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat other = (com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat) obj;

      boolean result = true;
      result = result && (hasRequestId() == other.hasRequestId());
      if (hasRequestId()) {
        result = result && (getRequestId()
            == other.getRequestId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestId()) {
        hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
        hash = (53 * hash) + getRequestId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * Protobuf type {@code message.HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.HeartBeat)
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.class, com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.Builder.class);
      }

      // Construct using com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_HeartBeat_descriptor;
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat getDefaultInstanceForType() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.getDefaultInstance();
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat build() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat buildPartial() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat result = new com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat) {
          return mergeFrom((com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat other) {
        if (other == com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int requestId_ ;
      /**
       * <code>required int32 requestId = 1;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 requestId = 1;</code>
       */
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <code>required int32 requestId = 1;</code>
       */
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.HeartBeat)
    }

    // @@protoc_insertion_point(class_scope:message.HeartBeat)
    private static final com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat();
    }

    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.HeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.Register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *注册类型
     * </pre>
     *
     * <code>required .message.RegType regType = 1;</code>
     */
    boolean hasRegType();
    /**
     * <pre>
     *注册类型
     * </pre>
     *
     * <code>required .message.RegType regType = 1;</code>
     */
    com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType getRegType();

    /**
     * <pre>
     *app信息
     * </pre>
     *
     * <code>required string appInfo = 2;</code>
     */
    boolean hasAppInfo();
    /**
     * <pre>
     *app信息
     * </pre>
     *
     * <code>required string appInfo = 2;</code>
     */
    java.lang.String getAppInfo();
    /**
     * <pre>
     *app信息
     * </pre>
     *
     * <code>required string appInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppInfoBytes();
  }
  /**
   * Protobuf type {@code message.Register}
   */
  public  static final class Register extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.Register)
      RegisterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Register.newBuilder() to construct.
    private Register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Register() {
      regType_ = 1;
      appInfo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType value = com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                regType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appInfo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_Register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.class, com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.Builder.class);
    }

    private int bitField0_;
    public static final int REGTYPE_FIELD_NUMBER = 1;
    private int regType_;
    /**
     * <pre>
     *注册类型
     * </pre>
     *
     * <code>required .message.RegType regType = 1;</code>
     */
    public boolean hasRegType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *注册类型
     * </pre>
     *
     * <code>required .message.RegType regType = 1;</code>
     */
    public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType getRegType() {
      com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType result = com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType.valueOf(regType_);
      return result == null ? com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType.LOCAL_CLIENT : result;
    }

    public static final int APPINFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object appInfo_;
    /**
     * <pre>
     *app信息
     * </pre>
     *
     * <code>required string appInfo = 2;</code>
     */
    public boolean hasAppInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *app信息
     * </pre>
     *
     * <code>required string appInfo = 2;</code>
     */
    public java.lang.String getAppInfo() {
      java.lang.Object ref = appInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *app信息
     * </pre>
     *
     * <code>required string appInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppInfoBytes() {
      java.lang.Object ref = appInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRegType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, regType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appInfo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, regType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register)) {
        return super.equals(obj);
      }
      com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register other = (com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register) obj;

      boolean result = true;
      result = result && (hasRegType() == other.hasRegType());
      if (hasRegType()) {
        result = result && regType_ == other.regType_;
      }
      result = result && (hasAppInfo() == other.hasAppInfo());
      if (hasAppInfo()) {
        result = result && getAppInfo()
            .equals(other.getAppInfo());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRegType()) {
        hash = (37 * hash) + REGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + regType_;
      }
      if (hasAppInfo()) {
        hash = (37 * hash) + APPINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAppInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.Register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.Register)
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_Register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_Register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.class, com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.Builder.class);
      }

      // Construct using com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        regType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        appInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_Register_descriptor;
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register getDefaultInstanceForType() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.getDefaultInstance();
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register build() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register buildPartial() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register result = new com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.regType_ = regType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appInfo_ = appInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register) {
          return mergeFrom((com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register other) {
        if (other == com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register.getDefaultInstance()) return this;
        if (other.hasRegType()) {
          setRegType(other.getRegType());
        }
        if (other.hasAppInfo()) {
          bitField0_ |= 0x00000002;
          appInfo_ = other.appInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRegType()) {
          return false;
        }
        if (!hasAppInfo()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int regType_ = 1;
      /**
       * <pre>
       *注册类型
       * </pre>
       *
       * <code>required .message.RegType regType = 1;</code>
       */
      public boolean hasRegType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *注册类型
       * </pre>
       *
       * <code>required .message.RegType regType = 1;</code>
       */
      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType getRegType() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType result = com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType.valueOf(regType_);
        return result == null ? com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType.LOCAL_CLIENT : result;
      }
      /**
       * <pre>
       *注册类型
       * </pre>
       *
       * <code>required .message.RegType regType = 1;</code>
       */
      public Builder setRegType(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.RegType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        regType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *注册类型
       * </pre>
       *
       * <code>required .message.RegType regType = 1;</code>
       */
      public Builder clearRegType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        regType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object appInfo_ = "";
      /**
       * <pre>
       *app信息
       * </pre>
       *
       * <code>required string appInfo = 2;</code>
       */
      public boolean hasAppInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *app信息
       * </pre>
       *
       * <code>required string appInfo = 2;</code>
       */
      public java.lang.String getAppInfo() {
        java.lang.Object ref = appInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *app信息
       * </pre>
       *
       * <code>required string appInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppInfoBytes() {
        java.lang.Object ref = appInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *app信息
       * </pre>
       *
       * <code>required string appInfo = 2;</code>
       */
      public Builder setAppInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *app信息
       * </pre>
       *
       * <code>required string appInfo = 2;</code>
       */
      public Builder clearAppInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appInfo_ = getDefaultInstance().getAppInfo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *app信息
       * </pre>
       *
       * <code>required string appInfo = 2;</code>
       */
      public Builder setAppInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appInfo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.Register)
    }

    // @@protoc_insertion_point(class_scope:message.Register)
    private static final com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register();
    }

    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Register>
        PARSER = new com.google.protobuf.AbstractParser<Register>() {
      public Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Register(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Register> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Register> getParserForType() {
      return PARSER;
    }

    public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.Register getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NormalMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.NormalMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code message.NormalMessage}
   */
  public  static final class NormalMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.NormalMessage)
      NormalMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NormalMessage.newBuilder() to construct.
    private NormalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NormalMessage() {
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NormalMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              content_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_NormalMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_NormalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.class, com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage)) {
        return super.equals(obj);
      }
      com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage other = (com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage) obj;

      boolean result = true;
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.NormalMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.NormalMessage)
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_NormalMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_NormalMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.class, com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.Builder.class);
      }

      // Construct using com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.internal_static_message_NormalMessage_descriptor;
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage getDefaultInstanceForType() {
        return com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.getDefaultInstance();
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage build() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage buildPartial() {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage result = new com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage) {
          return mergeFrom((com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage other) {
        if (other == com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message.NormalMessage)
    }

    // @@protoc_insertion_point(class_scope:message.NormalMessage)
    private static final com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage();
    }

    public static com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NormalMessage>
        PARSER = new com.google.protobuf.AbstractParser<NormalMessage>() {
      public NormalMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NormalMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NormalMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NormalMessage> getParserForType() {
      return PARSER;
    }

    public com.netflix.hystrix.dashboard.data.netty.protobuf.Message.NormalMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_HeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_HeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Register_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_Register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_NormalMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_NormalMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\007message\"\036\n\tHeartBeat\022\021\n" +
      "\trequestId\030\001 \002(\005\">\n\010Register\022!\n\007regType\030" +
      "\001 \002(\0162\020.message.RegType\022\017\n\007appInfo\030\002 \002(\t" +
      "\" \n\rNormalMessage\022\017\n\007content\030\001 \001(\t*-\n\007Re" +
      "gType\022\020\n\014LOCAL_CLIENT\020\001\022\020\n\014PROXY_CLIENT\020" +
      "\002B<\n1com.netflix.hystrix.dashboard.data." +
      "netty.protobufB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_HeartBeat_descriptor,
        new java.lang.String[] { "RequestId", });
    internal_static_message_Register_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_Register_descriptor,
        new java.lang.String[] { "RegType", "AppInfo", });
    internal_static_message_NormalMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_NormalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_NormalMessage_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
